let allMusic = [
    {"name": "ACDC (Overworld)","files": ["ACDC Town-BN1.ogg"], "author": "D3str0y3d","credit": false,"game": "BN1","duration": "1:58"},
    {"name": "School (Overworld)","files": ["School-BN1.ogg"], "author": "D3str0y3d","credit": false,"game": "BN1","duration": "1:28"},
    {"name": "Indoors (Overworld)","files": ["Indoors-BN1.ogg"], "author": "D3str0y3d","credit": false,"game": "BN1","duration": "0:26"},
    {"name": "School Comp","files": ["School Comp-BN1.ogg"], "author": "Indiana","credit": false,"game": "BN1","duration": "1:49"},
    {"name": "Oven Comp","files": ["Oven Comp-BN1.ogg"], "author": "Indiana","credit": false,"game": "BN1","duration": "1:53"},
    {"name": "Waterworks Comp","files": ["Waterworks-BN1.ogg"], "author": "D3str0y3d","credit": false,"game": "BN1","duration": "1:57"},
    {"name": "Power Plant Comp","files": ["Powerplant Comp-BN1.ogg"], "author": "D3str0y3d","credit": false,"game": "BN1","duration": "1:42"},
    {"name": "Traffic Light Comp","files": ["Traffic Light Comp-BN1.ogg"], "author": "D3str0y3d","credit": false,"game": "BN1","duration": "1:27"},
    {"name": "WWW Comp","files": ["WWW Comp-BN1.ogg"], "author": "D3str0y3d","credit": false,"game": "BN1","duration": "1:53"},
    {"name": "Internet Theme","files": ["Internet Theme-BN1.ogg"], "author": "Indiana","credit": false,"game": "BN1","duration": "1:39"},
    {"name": "Battle Theme","files": ["Battle Theme-BN1.ogg"], "author": "D3str0y3d","credit": false,"game": "BN1","duration": "1:44"},
    {"name": "Boss Theme","files": ["Boss Theme-BN1.ogg"], "author": "D3str0y3d","credit": false,"game": "BN1","duration": "1:30"},
    {"name": "Final Battle Theme","files": ["Finale Battle-BN1.ogg"], "author": "D3str0y3d","credit": false,"game": "BN1","duration": "1:49"},
    {"name": "ACDC (Overworld)","files": ["ACDC Town-BN2.ogg"], "author": "D3str0y3d","credit": false,"game": "BN2","duration": "1:59"},
    {"name": "Okuden (Overworld)","files": ["BN2-Okuden.ogg"], "author": "D3str0y3d","credit": false,"game": "BN2","duration": "1:28"},
    {"name": "Marine Harbor (Overworld)","files": ["BN2-Marine Harbor.ogg"], "author": "D3str0y3d","credit": false,"game": "BN2","duration": "1:20"},
    {"name": "Official Center (Overworld)","files": ["BN2-Official Center.ogg"], "author": "D3str0y3d","credit": false,"game": "BN2","duration": "1:08"},
    {"name": "Airport (Overworld)","files": ["BN2-Airport.ogg"], "author": "D3str0y3d","credit": false,"game": "BN2","duration": "2:06"},
    {"name": "Netopia City (Overworld)","files": ["BN2-Netopia.ogg"], "author": "D3str0y3d","credit": false,"game": "BN2","duration": "1:36"},
    {"name": "Netopia Castle (Overworld)","files": ["BN2-Netopia Castle.ogg"], "author": "D3str0y3d","credit": false,"game": "BN2","duration": "1:25"},
    {"name": "Netopia Alley (Overworld)","files": ["BN2-NetopiaAlley.ogg"], "author": "D3str0y3d","credit": false,"game": "BN2","duration": "0:26"},
    {"name": "Netopia Dungeon (Overworld)","files": ["BN2-Netopia Dungeon.ogg"], "author": "D3str0y3d","credit": false,"game": "BN2","duration": "2:06"},
    {"name": "Netopia Airport (Overworld)","files": ["BN2-NAL Airport.ogg"], "author": "D3str0y3d","credit": false,"game": "BN2","duration": "0:50"},
    {"name": "kotobuki (Overworld)","files": ["BN2-Kotubuki.ogg"], "author": "D3str0y3d","credit": false,"game": "BN2","duration": "1:09"},
    {"name": "Gas Comp","files": ["BN2-Gas Comp.ogg"], "author": "D3str0y3d","credit": false,"game": "BN2","duration": "1:28"},
    {"name": "Bomb Comp","files": ["BN2-BomComp.ogg"], "author": "D3str0y3d","credit": false,"game": "BN2","duration": "1:59"},
    {"name": "Mother Tree Comp","files": ["BN2-Mother Tree Comp.ogg"], "author": "D3str0y3d","credit": false,"game": "BN2","duration": "1:56"},
    {"name": "Castle Comp","files": ["BN2-Csstle Comp.ogg"], "author": "D3str0y3d","credit": false,"game": "BN2","duration": "1:11"},
    {"name": "Air Comp","files": ["BN2-AirComp.ogg"], "author": "D3str0y3d","credit": false,"game": "BN2","duration": "1:13"},
    {"name": "Gospel Comp","files": ["BN2-Gospel Comp.ogg"], "author": "D3str0y3d","credit": false,"game": "BN2","duration": "1:21"},
    {"name": "Internet Theme","files": ["BN2-Internet Theme.ogg"], "author": "D3str0y3d","credit": false,"game": "BN2","duration": "1:41"},
    {"name": "Undernet Theme","files": ["BN2-Undernet Theme.ogg"], "author": "D3str0y3d","credit": false,"game": "BN2","duration": "1:34"},
    {"name": "WWW Area","files": ["BN2-WWW Area.ogg"], "author": "D3str0y3d","credit": false,"game": "BN2","duration": "1:30"},
    {"name": "Battle Theme","files": ["BN2-Battle Theme.ogg"], "author": "D3str0y3d","credit": false,"game": "BN2","duration": "1:19"},
    {"name": "Boss Theme","files": ["BN2-Boss Theme.ogg"], "author": "D3str0y3d","credit": false,"game": "BN2","duration": "1:24"},
    {"name": "Final Battle Theme","files": ["BN2-Final Battle Theme.ogg"], "author": "D3str0y3d","credit": false,"game": "BN2","duration": "1:33"},

    ];
