let allNPCs = [

    {"name":"Cyber Bat","files":["cyber_bat.animation","cyber_bat.png"],"author":["Indiana","Keristero"],"game":"EXE4/BN4","preview":"cyber_bat.animation"},
    {"name":"Mr. Prog (Santa)","files":["progsmas.animation","progsmas.png","mug.animation","progsmas-mug.png"],"author":"unknown","game":"Custom","preview":"progsmas.animation"},
    {"name":"Mettaur Swing","files":["MetSwing.animation","MetSwing.png","mug.animation","mettaur-mug.png"],"author":"D3str0y3d","game":"Custom","preview":"MetSwing.animation"},
    {"name":"Bass","files":["bass.animation","bass.png","mug.animation","bass-mug.png"],"author":"unknown","game":"EXE6/BN6","preview":"bass.animation"},
    {"name": "Acid Ace","files": ["acid-ace-sf3.animation", "acid-ace-sf3.png","mug.animation","acid-ace-sf3-mug.png"],"author": "unknown","game": "SSR3/SF3","preview": "acid-ace-sf3.animation"},
    {"name": "Acid","files": ["acid-sf3.animation", "acid-sf3.png","mug.animation","acid-sf3-mug.png"],"author": "unknown","game": "SSR3/SF3","preview": "acid-sf3.animation"},
    {"name": "Alpha","files": ["alpha.animation", "alpha.png","mug.animation","alpha-mug.png"],"author": "unknown","game": "EXE3/BN3","preview": "alpha.animation"},
    {"name": "Angel Fm","files": ["angel-fm-sf2.animation", "angel-fm-sf2.png","mug.animation"],"author": "unknown","game": "SSR2/SF2","preview": "angel-fm-sf2.animation"},
    {"name": "Aquaman","files": ["aquaman.animation", "aquaman.png","mug.animation","aquaman-mug.png"],"author": "unknown","game": "EXE6/BN6","preview": "aquaman.animation"},
    {"name": "Bandit (Thief)","files": ["bandit-thief-bn2.animation", "bandit-thief-bn2.png","mug.animation"],"author": "unknown","game": "EXE2/BN2","preview": "bandit-thief-bn2.animation"},
    {"name": "Bandit (Vampire)","files": ["bandit-vampire-bn2.animation", "bandit-vampire-bn2.png","mug.animation"],"author": "unknown","game": "EXE2/BN2","preview": "bandit-vampire-bn2.animation"},
    {"name": "Bandit (Zombie)","files": ["bandit-zombie-bn2.animation", "bandit-zombie-bn2.png","mug.animation"],"author": "unknown","game": "EXE2/BN2","preview": "bandit-zombie-bn2.animation"},
    {"name": "Bass","files": ["BassBn3.animation", "BassBn3.png","BassBn3-mug.animation","BassBn3-mug.png"],"author": "unknown","game": "EXE3/BN3","preview": "BassBn3.animation"},
    {"name": "Beeg Fm","files": ["beeg-fm-sf3.animation", "beeg-fm-sf3.png","mug.animation"],"author": "unknown","game": "SSR3/SF3","preview": "beeg-fm-sf3.animation"},
    {"name": "Burai","files": ["burai-sf3.animation", "burai-sf3.png","mug.animation","burai-sf3-mug.png"],"author": "unknown","game": "SSR3/SF3","preview": "burai-sf3.animation"},
    {"name": "Dark Navi","files": ["dark-navi-shanghai.animation", "dark-navi-shanghai.png","mug.animation","dark-navi-shanghai-mug.png"],"author": "unknown","game": "Shanghai","preview": "dark-navi-shanghai.animation"},
    {"name": "Dark Roll","files": ["dark-roll.animation", "dark-roll.png","mug.animation","dark-roll-mug.png"],"author": "unknown","game": "Custom","preview": "dark-roll.animation"},
    {"name": "Mr. Prog (Dark Ninja)","files": ["darkprog-ninja.animation", "darkprog-ninja.png","mug.animation","darkprog-ninja-mug.png"],"author": "unknown","game": "Custom","preview": "darkprog-ninja.animation"},
    {"name": "Denpa Warp","files": ["denpa-warp-sf2.animation", "denpa-warp-sf2.png","mug.animation","denpa-warp-sf2-mug.png"],"author": "unknown","game": "SSR2/SF2","preview": "denpa-warp-sf2.animation"},
    {"name": "Elecman","files": ["elecman.animation", "elecman.png","mug.animation","elecman-mug.png"],"author": "unknown","game": "Other","preview": "elecman.animation"},
    {"name": "Eraseman","files": ["eraseman-bn6.animation", "eraseman-bn6.png","mug.animation","eraseman-bn6-mug.png"],"author": "unknown","game": "EXE6/BN6","preview": "eraseman-bn6.animation"},
    {"name": "Female Navi Orange","files": ["female-navi-exe4_orange.animation", "female-navi-exe4_orange.png","mug.animation","female-navi-exe4_orange-mug.png"],"author": "unknown","game": "EXE4/BN4","preview": "female-navi-exe4_orange.animation"},
    {"name": "Female Navi Purple","files": ["female-navi-exe5_purple.animation", "female-navi-exe5_purple.png","mug.animation","female-navi-exe5_purple-mug.png"],"author": "unknown","game": "EXE5/BN5","preview": "female-navi-exe5_purple.animation"},
    {"name": "Female Navi Pink","files": ["female-navi-exe6_pink.animation", "female-navi-exe6_pink.png","mug.animation","female-navi-exe6_pink-mug.png"],"author": "unknown","game": "EXE6/BN6","preview": "female-navi-exe6_pink.animation"},
    {"name": "Female Navi Yellow","files": ["female-navi-exe6_yellow.animation", "female-navi-exe6_yellow.png","mug.animation","female-navi-exe6_yellow-mug.png"],"author": "unknown","game": "EXE6/BN6","preview": "female-navi-exe6_yellow.animation"},
    {"name": "Fireman","files": ["fireman-bn45.animation", "fireman-bn45.png","mug.animation","fireman-bn45-mug.png"],"author": "unknown","game": "EXE4.5","preview": "fireman-bn45.animation"},
    {"name": "Flameman (Idle)","files": ["flameman-bn3-idle-only.animation", "flameman-bn3-idle-only.png","mug.animation","flameman-bn3-idle-only-mug.png"],"author": "unknown","game": "EXE3/BN3","preview": "flameman-bn3-idle-only.animation"},
    {"name": "Glyde (Idle)","files": ["Glyde_EXE4.animation", "Glyde_EXE4.png","mug.animation","Glyde_EXE4-mug.png"],"author": "unknown","game": "EXE4/BN4","preview": "Glyde_EXE4.animation"},
    {"name": "Navi - Green","files": ["green-white-normal-shanghai.animation", "green-white-normal-shanghai.png","mug.animation","green-white-normal-shanghai-mug.png"],"author": "unknown","game": "Shanghai","preview": "green-white-normal-shanghai.animation"},
    {"name": "Gutsman","files": ["gutsman.animation", "gutsman.png","mug.animation","gutsman-mug.png"],"author": "unknown","game": "Other","preview": "gutsman.animation"},
    {"name": "Heel Fm","files": ["heel-fm-sf1.animation", "heel-fm-sf1.png","mug.animation","heel-fm-sf1-mug.png"],"author": "unknown","game": "SSR1/SF1","preview": "heel-fm-sf1.animation"},
    {"name": "Heel Navi","files": ["heel-navi-bn3.animation", "heel-navi-bn3.png","mug.animation","heel-navi-bn3-mug.png"],"author": "unknown","game": "EXE3/BN3","preview": "heel-navi-bn3.animation"},
    {"name": "Heel Navi Black","files": ["heel-navi-exe4_black.animation", "heel-navi-exe4_black.png","mug.animation","heel-navi-exe4_black-mug.png"],"author": "unknown","game": "EXE4/BN4","preview": "heel-navi-exe4_black.animation"},
    {"name": "Heel Navi Purple","files": ["heel-navi-exe4_purple.animation", "heel-navi-exe4_purple.png","mug.animation","heel-navi-exe4_purple-mug.png"],"author": "unknown","game": "EXE4/BN4","preview": "heel-navi-exe4_purple.animation"},
    {"name": "Mr. Prog (Holy)","files": ["holyprog.animation", "holyprog.png","mug.animation","holyprog-mug.png"],"author": "unknown","game": "Custom","preview": "holyprog.animation"},
    {"name": "Iceman","files": ["iceman.animation", "iceman.png","mug.animation","iceman-mug.png"],"author": "unknown","game": "Other","preview": "iceman.animation"},
    {"name": "Laplace","files": ["laplace-sf3.animation", "laplace-sf3.png","mug.animation","laplace-sf3-mug.png"],"author": "unknown","game": "SSR3/SF3","preview": "laplace-sf3.animation"},
    {"name": "Magtect (Virus)","files": ["magtect-bn45.animation", "magtect-bn45.png","mug.animation"],"author": "unknown","game": "EXE4.5","preview": "magtect-bn45.animation"},
    {"name": "Male Navi Pink","files": ["male-navi-exe4_pink.animation", "male-navi-exe4_pink.png","mug.animation","male-navi-exe4_pink-mug.png"],"author": "unknown","game": "EXE4/BN4","preview": "male-navi-exe4_pink.animation"},
    {"name": "Male Navi Teal","files": ["male-navi-exe6_teal.animation", "male-navi-exe6_teal.png","mug.animation","male-navi-exe6_teal-mug.png"],"author": "unknown","game": "EXE6/BN6","preview": "male-navi-exe6_teal.animation"},
    {"name": "Megaman","files": ["megaman.animation", "megaman.png","mug.animation","megaman-mug.png"],"author": "unknown","game": "EXE6/BN6","preview": "megaman.animation"},
    {"name": "Mettaur (Virus)","files": ["mettaur-bn45.animation", "mettaur-bn45.png","mug.animation","mettaur-mug.png"],"author": "unknown","game": "EXE4.5","preview": "mettaur-bn45.animation"},
    {"name": "Lan","files": ["Netto-EXE3.animation", "Netto-EXE3.png","Netto-EXE3-mug.animation","Netto-EXE3-mug.png"],"author": "unknown","game": "EXE3/BN3","preview": "Netto-EXE3.animation"},
    {"name": "Normal Navi Brown","files": ["normal-navi-bn4_brown.animation", "normal-navi-bn4_brown.png","mug.animation","normal-navi-bn4_brown-mug.png"],"author": "unknown","game": "EXE4/BN4","preview": "normal-navi-bn4_brown.animation"},
    {"name": "Normal Navi Green","files": ["normal-navi-bn4_green.animation", "normal-navi-bn4_green.png","mug.animation","normal-navi-bn4_green-mug.png"],"author": "unknown","game": "EXE4/BN4","preview": "normal-navi-bn4_green.animation"},
    {"name": "Normal Navi Red","files": ["normal-navi-bn4_red.animation", "normal-navi-bn4_red.png","mug.animation","normal-navi-bn4_red-mug.png"],"author": "unknown","game": "EXE4/BN4","preview": "normal-navi-bn4_red.animation"},
    {"name": "Nurse Navi","files": ["Nurse Navi.animation", "Nurse Navi.png","mug.animation","Nurse Navi-mug.png"],"author": "unknown","game": "Other","preview": "Nurse Navi.animation"},
    {"name": "Official Navi","files": ["official-navi-exe4_orange.animation", "official-navi-exe4_orange.png","mug.animation","official-navi-exe4_orange-mug.png"],"author": "unknown","game": "EXE4/BN4","preview": "official-navi-exe4_orange.animation"},
    {"name": "Official Navi","files": ["official-navi-exe6_orange.animation", "official-navi-exe6_orange.png","mug.animation","official-navi-exe6_orange-mug.png"],"author": "unknown","game": "EXE6/BN6","preview": "official-navi-exe6_orange.animation"},
    {"name": "Navi - Orange","files": ["orange-normal-shanghai.animation", "orange-normal-shanghai.png","mug.animation","orange-normal-shanghai-mug.png"],"author": "unknown","game": "Shanghai","preview": "orange-normal-shanghai.animation"},
    {"name": "Official Navi","files": ["orange-official-bn3.animation", "orange-official-bn3.png","mug.animation","orange-official-bn3-mug.png"],"author": "unknown","game": "EXE3/BN3","preview": "orange-official-bn3.animation"},
    {"name": "Navi - Pink","files": ["pink-navi-shanghai.animation", "pink-navi-shanghai.png","mug.animation","pink-navi-shanghai-mug.png"],"author": "unknown","game": "Shanghai","preview": "pink-navi-shanghai.animation"},
    {"name": "Mr. Prog (Farmer)","files": ["prog-farmer.animation", "prog-farmer.png","mug.animation","prog-farmer-mug.png"],"author": "unknown","game": "Custom","preview": "prog-farmer.animation"},
    {"name": "Mr. Prog (Gold)","files": ["prog-gold.animation", "prog-gold.png","mug.animation","prog-gold-mug.png"],"author": "unknown","game": "EXE5/BN5","preview": "prog-gold.animation"},
    {"name": "Mr. Prog (Ninja)","files": ["prog-ninja.animation", "prog-ninja.png","mug.animation","prog-ninja-mug.png"],"author": "unknown","game": "EXE5/BN5","preview": "prog-ninja.animation"},
    {"name": "Mr. Prog","files": ["prog.animation", "prog.png","mug.animation","prog-mug.png"],"author": "unknown","game": "Other","preview": "prog.animation"},
    {"name": "Protoman","files": ["protoman-bn5.animation", "protoman-bn5.png","mug.animation","protoman-bn5-mug.png"],"author": "unknown","game": "EXE5/BN5","preview": "protoman-bn5.animation"},
    {"name": "Punk Navi","files": ["punk-navi-exe6_navy.animation", "punk-navi-exe6_navy.png","mug.animation","punk-navi-exe6_navy-mug.png"],"author": "unknown","game": "EXE6/BN6","preview": "punk-navi-exe6_navy.animation"},
    {"name": "Punk Navi - Red","files": ["punk-navi-exe6_red.animation", "punk-navi-exe6_red.png","mug.animation","punk-navi-exe6_red-mug.png"],"author": "unknown","game": "EXE6/BN6","preview": "punk-navi-exe6_red.animation"},
    {"name": "Navi - Purple","files": ["purple-navi-shanghai.animation", "purple-navi-shanghai.png","mug.animation","purple-navi-shanghai-mug.png"],"author": "unknown","game": "Shanghai","preview": "purple-navi-shanghai.animation"},
    {"name": "Ranked Navi","files": ["ranked-navi-bn3.animation", "ranked-navi-bn3.png","mug.animation","ranked-navi-bn3-mug.png"],"author": "unknown","game": "EXE3/BN3","preview": "ranked-navi-bn3.animation"},
    {"name": "Mr. Prog (Red)","files": ["red-prog.animation", "red-prog.png","mug.animation","red-prog-mug.png"],"author": "unknown","game": "Custom","preview": "red-prog.animation"},
    {"name": "Navi - Red Short","files": ["red-short-navi-shanghai.animation", "red-short-navi-shanghai.png","mug.animation","red-short-navi-shanghai-mug.png"],"author": "unknown","game": "Shanghai","preview": "red-short-navi-shanghai.animation"},
    {"name": "Roll","files": ["roll.animation", "roll.png","mug.animation","roll-mug.png"],"author": "unknown","game": "EXE4/BN4","preview": "roll.animation"},
    {"name": "Shademan","files": ["shademan-exe5.animation", "shademan-exe5.png","shademan-exe5-mug.animation","shademan-exe5-mug.png"],"author": "unknown","game": "EXE5/BN5","preview": "shademan-exe5.animation"},
    {"name": "Mr. Prog (Sir)","files": ["sirprog.animation", "sirprog.png","mug.animation","sirprog-mug.png"],"author": "unknown","game": "Custom","preview": "sirprog.animation"},
    {"name": "Sprite","files": ["sprite-shanghai.animation", "sprite-shanghai.png","mug.animation","sprite-shanghai-mug.png"],"author": "unknown","game": "Shanghai","preview": "sprite-shanghai.animation"},
    {"name": "Starman","files": ["starman.animation", "starman.png","mug.animation","starman-mug.png"],"author": "unknown","game": "Other","preview": "starman.animation"},
    {"name": "Sumo","files": ["sumo-bn5.animation", "sumo-bn5.png","mug.animation"],"author": "unknown","game": "EXE5/BN5","preview": "sumo-bn5.animation"},
    {"name": "Toadman","files": ["toadman.animation", "toadman.png","mug.animation","toadman-mug.png"],"author": "unknown","game": "Other","preview": "toadman.animation"},
    {"name": "Tomahawk","files": ["tomahawk.animation", "tomahawk.png","mug.animation","tomahawk-mug.png"],"author": "unknown","game": "Other","preview": "tomahawk.animation"},
    {"name": "Undernet Navi","files": ["undernet-navi-shanghai.animation", "undernet-navi-shanghai.png","mug.animation","undernet-navi-shanghai-mug.png"],"author": "unknown","game": "Shanghai","preview": "undernet-navi-shanghai.animation"},
    {"name": "Wily","files": ["wily.animation", "wily.png","mug.animation","wily-mug.png"],"author": ["unknown","Indiana (tweaks)"],"game": "EXE3/BN3","preview": "wily.animation"},
    {"name": "Windman","files": ["windman.animation", "windman.png","mug.animation","windman-mug.png"],"author": "unknown","game": "Other","preview": "windman.animation"},
    {"name": "Woodman","files": ["woodman.animation", "woodman.png","mug.animation","woodman-mug.png"],"author": "unknown","game": "Other","preview": "woodman.animation"}
  
/*
    //this is an empty dictionary you can use to make new entries

    {"name":"","files":["",""],"author":"","game":"","preview":""},

*/
];
