let allScripts = [
    { "name": "ezLibs", "description": 'At the heart of most major ONB servers, this suite of scripts makes adding mystery data, security cubes, player memory, warps, NPCs and so much more a breeze. Check out the documentation on the ezLibs Scripts repository, but consider using the self updating ezLibs server template as your starting point for your next ONB server. <br><br><button id="download-single-script"><a href="http://github.com/keristero/ezlibs-scripts" target="_blank" style="text-decoration:none; color:#000;">ezLibs Scripts</a></button>  &nbsp; <button id="download-single-script"><a href="http://github.com/keristero/ezlibs-assets" target="_blank" style="text-decoration:none; color:#000;">ezLibs Assets</a></button>  &nbsp; <button id="download-single-script"><a href="https://github.com/Keristero/onb-server-template" target="_blank" style="text-decoration:none; color:#000;">Server Template</a></button> ', "author": "Keristero", "scripttype": "Lua Script", "id": "ezlibs-keristero" },
    { "name": "Jukebox", "description": 'It\'s as groovy as it sounds, this script allows you to add a fully functional jukebox to your ONB server. You can configure the songs and let players jazz it up to their heart\'s content. There is a server template below if you want to try it before adding it to your own server.<br><br><button id="download-single-script"><a href="https://github.com/ninjaman255/Jukebox" target="_blank" style="text-decoration:none; color:#000;">Repository</a></button> &nbsp; <button id="download-single-script"><a href="https://discord.com/channels/455429604455219211/1195361353905479740/1195361353905479740" target="_blank" style="text-decoration:none; color:#000;">Documentation</a></button> &nbsp; <!--<button id="download-single-script"><a href="https://cdn.discordapp.com/attachments/1195361353905479740/1195361355230892062/JukeboxScript-V1.zip?ex=68404c83&is=683efb03&hm=5571edf10f2e5d42266e8b6729b2278ab77b4b12bebfce36b21eda9559b64bee&" target="_blank" style="text-decoration:none; color:#000;">Download Script</a></button>-->', "author": "D3str0y3d", "scripttype": "Lua Script", "id": "jukebox-d3" },
    { "name": 'Liberation Missions', "description": 'This script allows you to add fully functional Liberation Missions from BN5 to any ONB server. This is a fairly complex script so I recommend you read over the documentation linked below and use the server template created by CyanMan.EXE and D3str0yed (again linked below). <br><br><button id="download-single-script"><a href="https://docs.google.com/document/d/1Bo7iWf4KcY1jL9yYfMa8bupP2PkYxxhusw5QYxQQnpE/edit?usp=sharing" target="_blank" style="text-decoration:none; color:#000;">Documentation</a></button> &nbsp; <button id="download-single-script"><a href="https://github.com/ninjaman255/Template-Liberation-Missions" target="_blank" style="text-decoration:none; color:#000;">Server Template</a></button>  &nbsp; <button id="download-single-script"><a href="https://github.com/RogueClaris/Nebulous-Liberations-Scripts" target="_blank" style="text-decoration:none; color:#000;">Repository</a></button>', "author": ["Claris (script)", "Konstinople (script)", "CyanMan.EXE (server)", "D3str0y3d (server)"], "scripttype": "Lua Script", "id": "lib-claris" },
    { "name": 'Advertise Server', "description": 'If you want to include your server on the <a href="https://keristero.github.io/onb-modsite/servers.html">ONB Server List</a> you can do so by adding and configuring this script to your ONB server. <br><br> <span style="color:red;"><i><b>Warning:</b></i></span> Your server\'s IP address will be made public so make sure you are comfortable with that before advertising your server.<br><br><button id="download-single-script"><a href="https://cdn.discordapp.com/attachments/1159691462171168819/1159691607021461514/advertise_server.zip?ex=68406439&is=683f12b9&hm=ce3d0058c1e8f7bd99a47cf24f9097c137ec92861cad0d804a2ba3b97cfd9dc1&" target="_blank" style="text-decoration:none; color:#000;">Download Script</a></button> &nbsp; <button id="download-single-script"><a href="https://discord.com/channels/455429604455219211/1142407812736090183/1142409145581056001" target="_blank" style="text-decoration:none; color:#000;">Documentation</a></button>', "author": "Keristero", "scripttype": "Lua Script", "id": "advertise-keristero" },

    { "name": 'Indy\'s Trains (Cyber Metro)', "description": 'A standalone script to easily add customizable cyber metro trains (from BN3/EXE3) to Open Net Battle servers. Features a Tiled extension for easy configuration, new sprites for the cyber metro trains and conductor, server-to-server trains, and more!<br><br><button id="download-single-script"><a href="https://github.com/indianajson/cyber-trains/" target="_blank" style="text-decoration:none; color:#000;">Repository</a></button><br><br><img src="img/other/metro.png" height=200 /><br>', "author": "Indiana", "scripttype": "Lua Script", "id": "trains-indiana" },

    {"name": 'Fishing Mini-Game',"description":'If you\'re looking for a reel good time then add this fintastic fishing mini-game to your server with custom graphics and an easy to install standalone script from ShaDisNX255.<br><br><button id="download-single-script"><a href="https://discord.com/channels/455429604455219211/1425305088456523786" target="_blank" style="text-decoration:none; color:#000;">Documentation</a></button><br><br><img src="img/other/fishing.png" height=200 /><br>',"author": "ShaDisNX255","scripttype":"Lua Script","id":"shadis-fish"},
    
    { "name": 'Gravy Yum', "description": 'This server features encounters, key items, farming, BBS board, and NPCs. It uses the ezlibs library for much of it\'s content. <i>Please remember</i> not to use any custom sprites/assets from this server unless given permission.<br><br><button id="download-single-script"><a href="https://github.com/Keristero/gravy-yum" target="_blank" style="text-decoration:none; color:#000;">Repository</a></button>', "author": "Keristero", "scripttype": "Server Code", "id": "gravy-keristero" },

    { "name": 'Dawn\'s Liberation Server', "description": 'This server features several maps, custom encounters, boss encounters, NPCs, encounters, mystery data, side quests, and liberation missions. <br><br><button id="download-single-script"><a href="http://github.com/ninjaman255/DawnLibServer" target="_blank" style="text-decoration:none; color:#000;">Repository</a></button>', "author": "Claris", "scripttype": "Server Code", "id": "dawn-lib" },

    { "name": 'PVP Matchmaking', "description": 'This script allows users to enter free (unranked) or ranked matchmaking queues, as well as, view a leaderboard based on performance by their fellow players.<br><br><button id="download-single-script"><a href="https://github.com/indianajson/octo-ranking" target="_blank" style="text-decoration:none; color:#000;">Repository</a></button>', "author": ["OctoChris", "Indiana (improvements)", "Keristero (emote script)"], "scripttype": "Lua Script", "id": "pvp-octo" },

    { "name": 'ShaDis HP', "description": 'This server features a BBS, whitelist, custom items, custom events, encounters, ice puzzles, server-to-server cyber metro, and more! <i>Please remember</i> not to use any custom sprites/assets from this server unless given permission.<br><br><button id="download-single-script"><a href="https://github.com/ShaDisNX255/shadis_hp" target="_blank" style="text-decoration:none; color:#000;">Repository</a></button>', "author": "ShaDisNX255", "scripttype": "Server Code", "id": "shadis-hp" },

    { "name": 'Simple Drops', "description": 'This script allows you to add customizable drop edges to ice tiles that cause a player to fall down to a layer below the tile.<br><br><button id="download-single-script"><a href="https://github.com/indianajson/simple-drops" target="_blank" style="text-decoration:none; color:#000;">Repository</a></button>', "author": "Indiana", "scripttype": "Lua Script", "id": "simple-drops" },

    { "name": 'The Block', "description": 'This server features huge sprawling custom areas, quests, many NPCs, difficult encounters, cyber-metro stations, and much more. <i>Please remember</i> not to use any custom sprites/assets from this server unless given permission.<br><br><button id="download-single-script"><a href="https://github.com/CyanmanEXE/CyanServerTheBlock/" target="_blank" style="text-decoration:none; color:#000;">Repository</a></button>', "author": "CyanMan.EXE", "scripttype": "Server Code", "id": "the-block" },

    { "name": 'The Undernet',
         "description": 'This server features quests, custom ranking system, a cyber-metro station, encounters, spawling custom area, many NPCs, and much more! <i>Please remember</i> not to use any custom sprites/assets from this server unless given permission.<br><br><button id="download-single-script"><a href="https://github.com/HeadDM/undernet-server" target="_blank" style="text-decoration:none; color:#000;">Repository</a></button>', "author": "Mannerek.EXE", "scripttype": "Server Code", "id": "undernet" }

    /*
    
    //this is an empty dictionary you can use to make new entries, it includes the code for the button in the description field. 


    {"name": '',"description":'<button id="download-single-script"><a href="" target="_blank" style="text-decoration:none; color:#000;"></a></button>',"author": "","scripttype":"Lua Script","id":""},
    
    */

];
