let allData = [
{"name":"Den Area Tiles","files":["BN2_ACDC.tsx","BN2_ACDC.png"],"author":"Quetzen","type":"tile","credit":true,"game":"BN2","preview":"BN2_ACDC.png"},
{"name":"Den Area Floor Square","files":["ACDC_Net_Tileset.png","ACDC_Net_Tileset.tsx"],"type":"tile","author":"unknown","credit":false,"game":"BN2","preview":"ACDC_Net_Tileset.png"},
{"name":"Security Cube","files":["bn6_securitycube.tsx","bn6_securitycube.png"],"author":"unknown","type":"object","credit":false,"game":"BN6","preview":"bn6_securitycube.png"},
{"name":"Security Cube (gray)","files":["bn6_cube_gray.tsx","bn6_cube_gray.png"],"author":"unknown","type":"object","credit":false,"game":"BN6","preview":"bn6_cube_gray.png"},
{"name":"Home Warp","files":["home warp.png","home warp.tsx"],"author":"unknown","type":"object","credit":false,"game":"BN5","preview":"home warp.png"},
{"name":"Mystery Data","files":["MysteryData.png","MysteryData.tsx"],"author":"unknown","type":"object","credit":false,"game":"BN4.5","preview":"MysteryData.png"},
{"name":"Internet5-8 Area Tiles","files":["ZeroAccountTileset.tsx","ZeroAccountTileset.png"],"author":"unknown","type":"tile","credit":false,"game":"BN4.5","preview":"ZeroAccountTileset.png"},
{"name":"Area Warps","files":["4_5Warps.png","4_5Warps.tsx"],"author":"unknown","type":"object","credit":false,"game":"BN4.5","preview":"4_5Warps.png"},
{"name":"Alpha Comp Tiles","files":["Alpha_Comp.png","Alpha_Comp.tsx"],"author":"unknown","type":"tile","credit":false,"game":"BN3","preview":"Alpha_Comp.png"},
{"name":"Oven Comp Tiles (custom)","files":["Cords.png","Cords.tsx"],"type":"tile","author":"Mint Flav","credit":false,"game":"BN1","preview":"Cords.png"},
{"name":"Oven Comp Honeycomb Tile (custom)","files":["OvenHoneycombs.tsx","ovenhoneycomb.png"],"type":"tile","author":"Mint Flav","credit":false,"game":"BN1","preview":"ovenhoneycomb.png"},
{"name":"Fireman Flames","files":["Fireman Flame.png","Fireman Flame.tsx"],"type":"object","author":"unknown","credit":false,"game":"BN1","preview":"Fireman Flame.png"},
{"name":"Traffic Light Comp Arrows","files":["TrafficArrows.png","TrafficArrows.tsx"],"type":"tile","author":"unknown","credit":false,"game":"BN1","preview":"TrafficArrows.png"},
{"name":"Traffic Light Comp Tiles","files":["TrafficFloor.png","TrafficFloor.tsx"],"type":"tile","author":"unknown","credit":false,"game":"BN1","preview":"TrafficFloor.png"},
{"name":"Net Square Tiles","files":["BN2SquareColorful.png","BN2SquareColorful.tsx"],"type":"tile","author":"unknown","credit":false,"game":"BN2","preview":"BN2SquareColorful.png"},
{"name":"Netopia Arrows Recolored","files":["Den_Exits.png","Den_Exits.tsx"],"type":"tile","author":"unknown","credit":false,"game":"BN2","preview":"Den_Exits.png"},
{"name":"Den Area Animated Overlays","files":["DenAreaTechAnimatedOverlay.png","DenAreaTechAnimatedOverlay.tsx"],"type":"tile","author":"unknown","credit":false,"game":"BN2","preview":"DenAreaTechAnimatedOverlay.png"},
{"name":"Netopia Arrows","type":"tile","files":["Exits Redux.png","Exits Redux.tsx"],"author":"unknown","credit":false,"game":"BN2","preview":"Exits Redux.png"},
{"name":"Net Square Transition Tile","files":["FlatRamp.png","FlatRamp.tsx"],"type":"tile","author":"unknown","credit":false,"game":"BN2","preview":"FlatRamp.png"},
{"name":"Raoul HP Tiles","files":["FloorTilesColorful.png","FloorTilesColorful.tsx"],"type":"tile","author":"unknown","credit":false,"game":"BN2","preview":"FloorTilesColorful.png"},
{"name":"Ice Tile Tops","files":["IceTileTopper.png","IceTileTopper.tsx"],"type":"tile","author":"unknown","credit":false,"game":"BN3","preview":"IceTileTopper.png"},
{"name":"Internet House Door","files":["Internet House.png","Internet House.tsx"],"type":"object","author":"unknown","credit":false,"game":"BN2","preview":"Internet House.png"},
{"name":"Netopia Tiles","files":["Netopia Tileset.png","Netopia Tileset.tsx"],"type":"tile","author":"unknown","credit":false,"game":"BN2","preview":"Netopia Tileset.png"},
{"name":"Netopia Conveyer Tile","files":["Netopia_Tileset_directional_paths.png","Netopia_Tileset_directional_paths.tsx"],"type":"tile","author":"unknown","credit":false,"game":"BN2","preview":"Netopia_Tileset_directional_paths.png"},
{"name":"Snow Tile Toppers","files":["SnowTileTopper.png","SnowTileTopper.tsx"],"type":"tile","author":"unknown","credit":false,"game":"BN3","preview":"SnowTileTopper.png"},
{"name":"Net Square Warps","files":["SquareWarpsA.png","SquareWarpsA.tsx"],"type":"object","author":"unknown","credit":false,"game":"BN2","preview":"SquareWarpsA.png"},
{"name":"Undernet Animated Tile Tops","files":["Bn2UndernetAnimatedTiles.tsx","Bn2UndernetAnimatedTiles.png"],"type":"tile","author":"unknown","credit":false,"game":"BN2","preview":"Bn2UndernetAnimatedTiles.png"},
{"name":"ACDC Arrows","files":["ACDC_Arrows.png","ACDC_Arrows.tsx"],"type":"tile","author":"unknown","credit":false,"game":"BN3","preview":"ACDC_Arrows.png"},
{"name":"Beach Area Conveyers","files":["Beach Arrows.png","Beach Arrows.tsx"],"type":"tile","author":"unknown","credit":false,"game":"BN3","preview":"Beach Arrows.png"},
{"name":"Beach Area Stairs","files":["Beach Stairs.png","Beach Stairs.tsx"],"type":"tile","author":"unknown","credit":false,"game":"BN3","preview":"Beach Stairs.png"},
{"name":"Beach Area Tiles","files":["Beach Tileset.png","Beach Tiles.tsx"],"type":"tile","author":"unknown","credit":false,"game":"BN3","preview":"Beach Tileset.png"},
{"name":"Beach Area Arrows","files":["Beach_Next_Area.png","Beach_Next_Area.tsx"],"type":"tile","author":"unknown","credit":false,"game":"BN3","preview":"Beach_Next_Area.png"},
{"name":"Beach Area Warp","files":["Beach_Warp.png","Beach_Warp.tsx"],"type":"object","type":"object","author":"unknown","credit":false,"game":"BN3","preview":"Beach_Warp.png"},
{"name":"ACDC Warp","files":["BN3ACDC1Warp.png","BN3ACDC1Warp.tsx"],"type":"object","author":"unknown","credit":false,"game":"BN3","preview":"BN3ACDC1Warp.png"},
{"name":"ACDC Square Warp","files":["BN3ACDCWarp2.png","BN3ACDCWarp2.tsx"],"type":"object","author":"unknown","credit":false,"game":"BN3","preview":"BN3ACDCWarp2.png"},
{"name":"Dex Panel","files":["BN3DexPanel.png","BN3DexPanel.tsx"],"type":"tile","author":"unknown","credit":false,"game":"BN3","preview":"BN3DexPanel.png"},
{"name":"Tamako Panel","files":["BN3TamakoPanel.png","BN3TamakoPanel.tsx"],"type":"tile","author":"unknown","credit":false,"game":"BN3","preview":"BN3TamakoPanel.png"},
{"name":"Yai Panel","files":["BN3YaiPanel.png","BN3YaiPanel.tsx"],"type":"tile","author":"unknown","credit":false,"game":"BN3","preview":"BN3YaiPanel.png"},
{"name":"Yoka Compression Roads","files":["CompressionRoadsYoka.png","CompressionRoadsYoka.tsx"],"type":"tile","author":"unknown","credit":false,"game":"BN3","preview":"CompressionRoadsYoka.png"},
{"name":"Cyber ail","files":["Cyber_Rail.png","Cyber_Rail.tsx"],"type":"tile","author":"unknown","credit":false,"game":"BN3","preview":"Cyber_Rail.png"},
{"name":"DrillMan Portal","files":["DrillManPortal36x46.png","DrillManPortal36x46.tsx"],"type":"object","author":"unknown","credit":false,"game":"BN3","preview":"DrillManPortal36x46.png"},
{"name":"BBS Board","files":["BBSOldFixed.png","BBSOldFixed.tsx"],"type":"object","author":"unknown","credit":false,"game":"BN3","preview":"BBSOldFixed.png"},
{"name":"BBS Board","files":["BBS-BN4.png","BBS-BN4.tsx"],"author":"unknown","credit":false,"game":"BN4","preview":"BBS-BN4.png"},
{"name":"BBS Board","files":["BBS.tsx","BBS.png"],"author":"unknown","type":"object","credit":false,"game":"BN6","preview":"BBS.png"},
{"name":"HP Tiles","files":["bn6_pc_tile.png","bn6_pc_tile.tsx"],"type":"tile","author":"unknown","credit":false,"game":"BN6","preview":"bn6_pc_tile.png"},
{"name":"Nebula Gate","type":"object","files":["nebula door.png","nebula door.tsx"],"author":"unknown","credit":false,"game":"BN5","preview":"nebula door.png"},
{"name":"Central Area Arrows (Blue)","type":"tile","files":["central_arrows.png","central_arrows.tsx"],"author":"unknown","credit":false,"game":"BN6","preview":"central_arrows.png"},
{"name":"Central Area Arrows (Yellow)","type":"tile","files":["central_arrows2.png","central_arrows2.tsx"],"author":"unknown","credit":false,"game":"BN6","preview":"central_arrows2.png"},
{"name":"Central Area Arrows (Cyan)","type":"tile","files":["central_arrows3.png","central_arrows3.tsx"],"author":"unknown","credit":false,"game":"BN6","preview":"central_arrows3.png"},
{"name":"Central Area Tiles","type":"tile","files":["central_platform.png","central_platform.tsx"],"author":"unknown","credit":false,"game":"BN6","preview":"central_platform.png"},
{"name":"Central Area 3 Pipe","type":"object","files":["Central3Pipe.png","Central3Pipe.tsx"],"author":"D3str0y3d","credit":false,"game":"BN6","preview":"Central3Pipe.png"},
{"name":"Central Area 3 Pipe Drip","type":"object","files":["water60x48Central3.png","water60x48Central3.tsx"],"author":"D3str0y3d","credit":false,"game":"BN6","preview":"water60x48Central3.png"},
{"name":"Central Area Square Tiles","type":"tile","files":["Custom_Central_Tiles.png","Custom_Central_Tiles.tsx"],"author":"unknown","credit":false,"game":"BN6","preview":"Custom_Central_Tiles.png"},
{"name":"Central Area Stairs","type":"tile","files":["DenTownStairs.png","DenTownStairs.tsx"],"author":"unknown","credit":false,"game":"BN6","preview":"DenTownStairs.png"},
{"name":"Mr Weather Comp Cloud Tile","type":"tile","files":["cloud.png","cloud.tsx"],"author":"unknown","credit":false,"game":"BN6","preview":"cloud.png"},
{"name":"Mr Weather Comp Dark Cloud Tile","type":"tile","files":["Oven Cloud.png","Oven Cloud.tsx"],"author":"unknown","credit":false,"game":"BN6","preview":"Oven Cloud.png"},
{"name":"Coffee Sign","type":"object","files":["coffee.png","coffee.tsx"],"author":"unknown","credit":false,"game":"BN6","preview":"coffee.png"},
{"name":"Duck","type":"object","files":["Ducky.png","Ducky.tsx"],"author":"unknown","credit":false,"game":"BN6","preview":"Ducky.png"},
{"name":"HP Assorted Tiles","type":"tile","files":["floor.png","floor.tsx"],"author":"unknown","credit":false,"game":"BN6","preview":"floor.png"},
{"name":"Home Warp","type":"object","files":["home_warp.png","home_warp.tsx"],"author":"unknown","credit":false,"game":"BN6","preview":"home_warp.png"},
{"name":"Mystery Data - Blue","type":"object","files":["BlueMysteryData.png","BlueMysteryData.tsx"],"author":"unknown","credit":false,"game":"BN6","preview":"BlueMysteryData.png"},
{"name":"Mystery Data - Green","type":"object","files":["GreenMysteryData.png","GreenMysteryData.tsx"],"author":"unknown","credit":false,"game":"BN6","preview":"GreenMysteryData.png"},
{"name":"Mystery Data - Purple","type":"object","files":["PurpleMysteryData.png","PurpleMysteryData.tsx"],"author":"unknown","credit":false,"game":"BN6","preview":"PurpleMysteryData.png"},
{"name":"HP Colored Tiles","type":"tile","files":["rainbow_floor.png","rainbow_floor.tsx"],"author":"unknown","credit":false,"game":"BN6","preview":"rainbow_floor.png"},
{"name":"Custom Conveyers","type":"tile","files":["simple-graveyard-conveyers-64-40-alt.png","simple-graveyard-conveyers-64-40-alt.tsx"],"author":"unknown","credit":false,"game":"Other","preview":"simple-graveyard-conveyers-64-40-alt.png"},
{"name":"Cyber Talisman","type":"object","files":["Talisman.png","Talisman.tsx"],"author":"unknown","credit":false,"game":"BN6","preview":"Talisman.png"},
{"name":"Cyber Teddy","type":"object","files":["Teddy.png","Teddy.tsx"],"author":"unknown","credit":false,"game":"BN6","preview":"Teddy.png"},
{"name":"Cyber Tree","type":"object","files":["tree.png","tree.tsx"],"author":"unknown","credit":false,"game":"BN6","preview":"tree.png"},
{"name":"Vender Desk","type":"object","files":["vendor_desk.png","vendor_desk.tsx"],"author":"unknown","credit":false,"game":"BN6","preview":"vendor_desk.png"},
{"name":"Shanghai Warps","type":"object","files":["ShanghaiWarps1.png","ShanghaiWarps1.tsx"],"type":"object","author":"unknown","credit":false,"game":"Shanghai","preview":"ShanghaiWarps1.png"},
{"name":"Netopia Recolored Tiles","type":"tile","files":["DenTownNet_Tileset.png","DenTownNet_Tileset.tsx"],"author":"unknown","credit":false,"game":"BN2","preview":"DenTownNet_Tileset.png"},
{"name":"Graveyard Backward Stairs","type":"tile","files":["cursed-stairs-2.png","cursed-stairs-2.tsx"],"author":"unknown","credit":false,"game":"BN6","preview":"cursed-stairs-2.png"},
{"name":"Netopia Backward Stairs","type":"tile","files":["cursed-stairs-Bn2.png","cursed-stairs-Bn2.tsx"],"author":"unknown","credit":false,"game":"BN2","preview":"cursed-stairs-Bn2.png"},
{"name":"Evil Door","type":"object","files":["evildoor_40x74.png","evildoor_40x74.tsx"],"author":"unknown","credit":false,"game":"BN4","preview":"evildoor_40x74.png"},
{"name":"Battle Machine","type":"object","files":["BattleMachineBN4.png","BattleMachineBN4.tsx"],"author":"unknown","credit":false,"game":"BN4","preview":"BattleMachineBN4.png"},
{"name":"Dark Chip","type":"object","files":["Darkchip13x32.png","Darkchip13x32.tsx"],"author":"unknown","credit":false,"game":"BN4","preview":"Darkchip13x32.png"},
{"name":"Yoka Custom Tiles","type":"tile","files":["yokaforjamestileset67x52.png","yokaforjamestileset67x52.tsx"],"type":"tile","author":"DigitalL33T","credit":false,"game":"BN3","preview":"yokaforjamestileset67x52.png"},
{"name":"Graveyard Stairs","type":"tile","files": ["UndernetStairs.png","UndernetStairs.tsx"],"author": "unknown","credit": false,"game": "BN6","preview": "UndernetStairs.png"},
{"name":"Graveyard Tiles","type":"tile","files": ["UndernetTiles.png","UndernetTiles.tsx"],"author": "unknown","credit": false,"game": "BN6","preview": "UndernetTiles.png"},
{"name":"Sky Area 2 Gate","type":"object","files":["Gate_sky2_exe6.png","Gate_sky2_exe6.tsx"],"author":"unknown","credit":false,"game":"BN6","preview":"Gate_sky2_exe6.png"},
{"name":"Server Warp Pads","files":["DungeonServerWarpPads.png","DungeonServerWarpPads.tsx"],"author":"unknown","credit":false,"game":"BN6","preview":"DungeonServerWarpPads.png"},
{"name":"Net Square Ramps","files":["Netopia_Stairs.png","Netopia_Stairs.tsx"],"author":"unknown","credit":false,"game":"BN2","preview":"Netopia_Stairs.png"},
{"name":"Libertaion Compatible Walls","type":"object","files":["lib_tileset_panels.png","lib_tileset_panels.tsx"],"author":"Quetzen","credit":false,"game":"BN5","preview":"lib_tileset_panels.png"},
{"name":"liberation Compatible Tileset","type":"tile","files":["lib_tileset.png","lib_tileset.tsx"],"author":"Quetzen","credit":false,"game":"BN5","preview":"lib_tileset.png"},
{"name":"Libertaion Panel Tile","type":"tile","files":["panelbase.png","panelbase.tsx"],"author":"unknown","credit":false,"game":"BN5","preview":"panelbase.png"},
{"name":"ACDC Tree","type":"object","files":["ACDC Tree.tsx","ACDC Tree.png"],"author":"unknown","credit":false,"game":"BN5","preview":"ACDC Tree.png"},
{"name":"Bug Frag Trader","type":"object","files":["BugFragTrader_exe3.png","BugFragTrader.tsx"],"author":"unknown","credit":false,"game":"BN3","preview":"BugFragTrader_exe3.png"},
{"name":"Breaker Moon Tiles","type":"tile","files":["BreakerMoonAnimated.png","BreakerMoonAnimated.tsx"],"author":"DigitalL33T","credit":false,"game":"Other","preview":"BreakerMoonAnimated.png"},
{"name":"Beach Area Warp Customized","files":["CusBeachWarp.png","CusBeachWarp.tsx"],"type":"object","author":"unknown","credit":false,"game":"BN3","preview":"CusBeachWarp.png"},
{"name":"Gate","type":"object","files":["gate.png","gate.tsx"],"author":"unknown","credit":false,"game":"BN6","preview":"gate.png"},
{"name":"Gospel Portal","type":"object","files":["GospelPortal.png","GospelPortal.tsx"],"author":"unknown","credit":false,"game":"BN2","preview":"GospelPortal.png"},


/*
{"name":"","type":"","files":["",""],"author":"unknown","credit":false,"game":"","preview":""},
"type":"object",
"type":"tile",
*/

/*
These need work
{"name":"Den Area Map Board (lower)","type":"object","files":["denArea2MapBoard.png","denArea2MapBoard.tsx"],"author":"unknown","credit":false,"game":"Other","preview":"denArea2MapBoard.png"},
{"name":"Den Area Map Board (upper)","type":"object","files":["denArea2MapBoard2.png","denArea2MapBoard2.tsx"],"author":"unknown","credit":false,"game":"Other","preview":"denArea2MapBoard2.png"},
*/

/*
missing TSX
{"name":"ElectricLock_exe5","files":["ElectricLock_exe5.png"],"author":"unknown","credit":false,"game":"BN5","preview":"ElectricLock_exe5.png"},

*/

];