let allData = [
{"name":"Den / ACDC Area Tiles","files":["BN2 ACDC.tsx","BN2 ACDC.png"],"author":"Quetzen","type":"tile","game":"EXE2/BN2","preview":"BN2 ACDC.png"},
//{"name":"Den Area Tile (Square)","files":["ACDC_Net_Tileset.png","ACDC_Net_Tileset.tsx"],"type":"tile","author":"Claris","game":"EXE2/BN2","preview":"ACDC_Net_Tileset.png"},
{"name":"Security Cube","files":["bn6_securitycube.tsx","bn6_securitycube.png"],"author":"Claris","type":"object","game":"EXE6/BN6","preview":"bn6_securitycube.png"},
{"name":"Security Cube (gray)","files":["bn6_cube_gray.tsx","bn6_cube_gray.png"],"author":"Claris","type":"object","game":"EXE6/BN6","preview":"bn6_cube_gray.png"},
{"name":"Home Warp","files":["home warp.png","home warp.tsx"],"author":"unknown","type":"object","game":"EXE5/BN5","preview":"home warp.png"},
{"name":"Mystery Data","files":["MysteryData.png","MysteryData.tsx"],"author":"unknown","type":"object","game":"EXE4.5","preview":"MysteryData.png"},
{"name":"Internet5-8 Area Tiles","files":["ZeroAccountTileset.tsx","ZeroAccountTileset.png"],"author":"unknown","type":"tile","game":"EXE4.5","preview":"ZeroAccountTileset.png"},
{"name":"Area Warps","files":["4_5Warps.png","4_5Warps.tsx"],"author":"unknown","type":"object","game":"EXE4.5","preview":"4_5Warps.png"},
{"name":"Liberation - Alpha Tileset (BN3)","type":"tiles","files":["AlphaAreaTileset.png","AlphaAreaTileset.tsx"],"author":"Quetzen","game":"Custom","preview":"AlphaAreaTileset.png"},
{"name":"Liberation - Alpha Panels (BN3)","type":"object","files":["alpha-liberation-panels.png","alpha-liberation-panels.tsx"],"author":["D3str0yed","Jawnii [Alcor/Kuri]"],"game":"Custom","preview":"alpha-liberation-panels.png"},
{"name":"Alpha Comp Tiles","files":["Alpha_Comp.png","Alpha_Comp.tsx"],"author":"Claris","type":"tile","game":"EXE3/BN3","preview":"Alpha_Comp.png"},
{"name":"Oven Comp Tiles (BN1)","files":["Cords.png","Cords.tsx"],"type":"tile","author":["Claris","Mint Flav","Rune","Alcor"],"game":"Custom","preview":"Cords.png"},
{"name":"Oven Comp Honeycomb Tile (BN1)","files":["OvenHoneycombs.tsx","ovenhoneycomb.png"],"type":"tile","author":"Mint Flav","game":"Custom","preview":"ovenhoneycomb.png"},
{"name":"Oven Comp Honeycomb Tile","type":"tile","files":["test-honey.tsx","test-honey.png"],"author":"Keristero","game":"EXE1/BN1","preview":"test-honey.png"},
{"name":"Fireman Flames","files":["Fireman Flame.png","Fireman Flame.tsx"],"type":"object","author":"unknown","game":"EXE1/BN1","preview":"Fireman Flame.png"},
{"name":"Traffic Light Comp Arrows","files":["TrafficArrows.png","TrafficArrows.tsx"],"type":"tile","author":"unknown","game":"EXE1/BN1","preview":"TrafficArrows.png"},
{"name":"Traffic Light Comp Tiles","files":["TrafficFloor.png","TrafficFloor.tsx"],"type":"tile","author":"unknown","game":"EXE1/BN1","preview":"TrafficFloor.png"},
{"name":"Net Square Tiles","files":["BN2SquareColorful.png","BN2SquareColorful.tsx"],"type":"tile","author":"unknown","game":"EXE2/BN2","preview":"BN2SquareColorful.png"},
{"name":"Net Square Transition Tile","files":["FlatRamp.png","FlatRamp.tsx"],"type":"tile","author":"unknown","game":"EXE2/BN2","preview":"FlatRamp.png"},
{"name":"Raoul HP Tiles","files":["FloorTilesColorful.png","FloorTilesColorful.tsx"],"type":"tile","author":"unknown","game":"EXE2/BN2","preview":"FloorTilesColorful.png"},
{"name":"Ice Tile Tops","files":["IceTileTopper.png","IceTileTopper.tsx"],"type":"tile","author":"unknown","game":"EXE3/BN3","preview":"IceTileTopper.png"},
{"name":"Internet House Door","files":["Internet House.png","Internet House.tsx"],"type":"object","author":"unknown","game":"EXE2/BN2","preview":"Internet House.png"},
{"name":"Netopia Tiles","files":["Netopia Tileset.png","Netopia Tileset.tsx"],"type":"tile","author":"Claris","game":"EXE2/BN2","preview":"Netopia Tileset.png"},
{"name":"Netopia Arrows","type":"tile","files":["Exits Redux.png","Exits Redux.tsx"],"author":"Claris","game":"EXE2/BN2","preview":"Exits Redux.png"},
{"name":"Netopia Conveyers","files":["Netopia_Tileset_directional_paths.png","Netopia_Tileset_directional_paths.tsx"],"type":"tile","author":"Claris","game":"EXE2/BN2","preview":"Netopia_Tileset_directional_paths.png"},
{"name":"Netopia Castle Wall Long","files":["Castle Wall Long.png","Castle Wall Long.tsx"],"author":"Claris","game":"Custom","preview":"Castle Wall Long.png"},
{"name":"Netopia Castle Wall","files":["Castle Wall.png","Castle Wall.tsx"],"author":"Claris","game":"Custom","preview":"Castle Wall.png"},
{"name":"Netopia Backward Stairs","type":"tile","files":["cursed-stairs-Bn2.png","cursed-stairs-Bn2.tsx"],"author":"unknown","game":"EXE2/BN2","preview":"cursed-stairs-Bn2.png"},
{"name":"Netopia Recolored Tiles","type":"tile","files":["DenTownNet_Tileset.png","DenTownNet_Tileset.tsx"],"author":"Claris","game":"EXE2/BN2","preview":"DenTownNet_Tileset.png"},
{"name":"Netopia Arrows Recolored","files":["Den_Exits.png","Den_Exits.tsx"],"type":"tile","author":"Claris","game":"EXE2/BN2","preview":"Den_Exits.png"},
{"name":"Snow Tile Toppers","files":["SnowTileTopper.png","SnowTileTopper.tsx"],"type":"tile","author":"unknown","game":"EXE3/BN3","preview":"SnowTileTopper.png"},
{"name":"Net Square Warps","files":["SquareWarpsA.png","SquareWarpsA.tsx"],"type":"object","author":"unknown","game":"EXE2/BN2","preview":"SquareWarpsA.png"},
{"name":"Undernet Animated Tile Tops","files":["Bn2UndernetAnimatedTiles.tsx","Bn2UndernetAnimatedTiles.png"],"type":"tile","author":"unknown","game":"EXE2/BN2","preview":"Bn2UndernetAnimatedTiles.png"},
{"name":"ACDC Arrows","files":["ACDC_Arrows.png","ACDC_Arrows.tsx"],"type":"tile","author":"unknown","game":"EXE3/BN3","preview":"ACDC_Arrows.png"},
{"name":"Beach Area Conveyers","files":["Beach Arrows.png","Beach Arrows.tsx"],"type":"tile","author":"Claris","game":"EXE3/BN3","preview":"Beach Arrows.png"},
{"name":"Beach Area Stairs","files":["Beach Stairs.png","Beach Stairs.tsx"],"type":"tile","author":"Claris","game":"EXE3/BN3","preview":"Beach Stairs.png"},
{"name":"Beach Area Tiles","files":["Beach Tileset.png","Beach Tileset.tsx"],"type":"tile","author":"Claris","game":"EXE3/BN3","preview":"Beach Tileset.png"},
{"name":"Beach Area Arrows","files":["Beach_Next_Area.png","Beach_Next_Area.tsx"],"type":"tile","author":"Claris","game":"EXE3/BN3","preview":"Beach_Next_Area.png"},
{"name":"Beach Area Warp","files":["Beach_Warp.png","Beach_Warp.tsx"],"type":"object","type":"object","author":"Claris","game":"EXE3/BN3","preview":"Beach_Warp.png"},
{"name":"SciLab Area Arrows (1 of 2)","files":["SciLabF1_Arrows.png","SciLabF1_Arrows.tsx"],"type":"tile","author":"unknown","game":"EXE3/BN3","preview":"SciLabF1_Arrows.png"},
{"name":"SciLab Area Arrows (2 of 2)","files":["SciLabF2_Arrows.png","SciLabF2_Arrows.tsx"],"type":"tile","author":"unknown","game":"EXE3/BN3","preview":"SciLabF2_Arrows.png"},
{"name":"Yoka Area Arrows (1 of 2)","files":["YokaF1_Arrows.png","YokaF1_Arrows.tsx"],"type":"tile","author":"unknown","game":"EXE3/BN3","preview":"YokaF1_Arrows.png"},
{"name":"Yoka Area Arrows (2 of 2)","files":["YokaF2_Arrows.png","YokaF2_Arrows.tsx"],"type":"tile","author":"unknown","game":"EXE3/BN3","preview":"YokaF2_Arrows.png"},
{"name":"Hades Arrows","files":["HadesF2_Arrows.png","HadesF2_Arrows.tsx"],"type":"tile","author":"unknown","game":"EXE3/BN3","preview":"HadesF2_Arrows.png"},
{"name":"Bass Door","files":["BassDoor.png","BassDoor.tsx"],"author":"unknown","game":"EXE3/BN3","preview":"BassDoor.png"},
{"name":"Spikey Gargoyle","files":["Spikey Gargoyle.png","Spikey Gargoyle.tsx"],"type":"tile","author":"unknown","game":"Other","preview":"Spikey Gargoyle.png"},
{"name":"Tombstone","files": ["Tombstone_exe6.png","Tombstone_exe6.tsx"],"author": "unknown","credit": false,"game": "EXE6/BN6","preview": "Tombstone_exe6.png"},
{"name":"Program Chip Form","type":"object","files":["ProgramChipForm.png","ProgramChipForm.tsx"],"author":"unknown","game":"Other","preview":"ProgramChipForm.png"},
{"name":"ACDC Warp","files":["BN3ACDC1Warp.png","BN3ACDC1Warp.tsx"],"type":"object","author":"unknown","game":"EXE3/BN3","preview":"BN3ACDC1Warp.png"},
{"name":"ACDC Square Warp","files":["BN3ACDCWarp2.png","BN3ACDCWarp2.tsx"],"type":"object","author":"unknown","game":"EXE3/BN3","preview":"BN3ACDCWarp2.png"},
{"name":"Dex Panel","files":["BN3DexPanel.png","BN3DexPanel.tsx"],"type":"tile","author":"unknown","game":"EXE3/BN3","preview":"BN3DexPanel.png"},
{"name":"Tamako Panel","files":["BN3TamakoPanel.png","BN3TamakoPanel.tsx"],"type":"tile","author":"unknown","game":"EXE3/BN3","preview":"BN3TamakoPanel.png"},
{"name":"Yai Panel","files":["BN3YaiPanel.png","BN3YaiPanel.tsx"],"type":"tile","author":"unknown","game":"EXE3/BN3","preview":"BN3YaiPanel.png"},
{"name":"Mayl Panel","files":["BN3MaylPanel.png","BN3MaylPanel.tsx"],"type":"tile","author":"FrozenLake","game":"EXE3/BN3","preview":"BN3MaylPanel.png"},
{"name":"Yoka Compression Roads","files":["CompressionRoadsYoka.png","CompressionRoadsYoka.tsx"],"type":"tile","author":["D3str0y3d","FrozenLake"],"game":"EXE3/BN3","preview":"CompressionRoadsYoka.png"},
{"name":"Yoka Compression Roads Shadows","type":"object","files":["ShadowCompressionRoad.png","ShadowCompressionRoad.tsx"],"author":"D3str0y3d","game":"EXE3/BN3","preview":"ShadowCompressionRoad.png"},
{"name":"Yoka Custom Tiles","type":"tile","files":["yokaforjamestileset67x52.png","yokaforjamestileset67x52.tsx"],"type":"tile","author":"DigitalL33T","game":"EXE3/BN3","preview":"yokaforjamestileset67x52.png"},
{"name":"Cyber Metro Rail","files":["Cyber_Rail.png","Cyber_Rail.tsx"],"type":"tile","author":"unknown","game":"EXE3/BN3","preview":"Cyber_Rail.png"},
{"name":"DrillMan Portal","files":["DrillManPortal36x46.png","DrillManPortal36x46.tsx"],"type":"object","author":"unknown","game":"EXE3/BN3","preview":"DrillManPortal36x46.png"},
{"name":"BBS Board","files":["BBSOldFixed.png","BBSOldFixed.tsx"],"type":"object","author":"unknown","game":"EXE3/BN3","preview":"BBSOldFixed.png"},
{"name":"BBS Board","files":["BBS-BN4.png","BBS-BN4.tsx"],"author":"unknown","game":"EXE4/BN4","preview":"BBS-BN4.png"},
{"name":"BBS Board","files":["BBS.tsx","BBS.png"],"author":"unknown","type":"object","game":"EXE6/BN6","preview":"BBS.png"},
{"name":"HP Tiles","files":["bn6_pc_tile.png","bn6_pc_tile.tsx"],"type":"tile","author":"unknown","game":"EXE6/BN6","preview":"bn6_pc_tile.png"},
{"name":"Nebula Gate","type":"object","files":["nebula door.png","nebula door.tsx"],"author":"unknown","game":"EXE5/BN5","preview":"nebula door.png"},
{"name":"Central Area Arrows (Blue)","type":"tile","files":["central_arrows.png","central_arrows.tsx"],"author":"unknown","game":"EXE6/BN6","preview":"central_arrows.png"},
{"name":"Central Area Arrows (Yellow)","type":"tile","files":["central_arrows2.png","central_arrows2.tsx"],"author":"unknown","game":"EXE6/BN6","preview":"central_arrows2.png"},
{"name":"Central Area Arrows (Cyan)","type":"tile","files":["central_arrows3.png","central_arrows3.tsx"],"author":"unknown","game":"EXE6/BN6","preview":"central_arrows3.png"},
{"name":"Central Area Tiles","type":"tile","files":["central_platform.png","central_platform.tsx"],"author":"Claris","game":"EXE6/BN6","preview":"central_platform.png"},
{"name":"Central Area 3 Pipe","type":"object","files":["Central3Pipe.png","Central3Pipe.tsx"],"author":"D3str0y3d","game":"EXE6/BN6","preview":"Central3Pipe.png"},
{"name":"Central 3 Pipe Empty","type":"object","files":["pump2.png","pump2.tsx"],"author":"Cyan","game":"EXE6/BN6","preview":"pump2.png"},
{"name":"Central Area 3 Pipe Drip","type":"object","files":["water60x48Central3.png","water60x48Central3.tsx"],"author":"D3str0y3d","game":"EXE6/BN6","preview":"water60x48Central3.png"},
{"name":"Central Area Square Tiles","type":"tile","files":["Custom_Central_Tiles.png","Custom_Central_Tiles.tsx"],"author":"Claris","game":"EXE6/BN6","preview":"Custom_Central_Tiles.png"},
{"name":"Central Area Stairs","type":"tile","files":["DenTownStairs.png","DenTownStairs.tsx"],"author":"unknown","game":"EXE6/BN6","preview":"DenTownStairs.png"},
{"name":"Mr Weather Comp Cloud Tile","type":"tile","files":["cloud.png","cloud.tsx"],"author":"unknown","game":"EXE6/BN6","preview":"cloud.png"},
{"name":"Mr Weather Comp Dark Cloud Tile","type":"tile","files":["Oven Cloud.png","Oven Cloud.tsx"],"author":"unknown","game":"EXE6/BN6","preview":"Oven Cloud.png"},
{"name":"Coffee Sign","type":"object","files":["coffee.png","coffee.tsx"],"author":"unknown","game":"EXE6/BN6","preview":"coffee.png"},
{"name":"HP Assorted Tiles","type":"tile","files":["floor.png","floor.tsx"],"author":"unknown","game":"EXE6/BN6","preview":"floor.png"},
{"name":"Home Warp","type":"object","files":["home_warp.png","home_warp.tsx"],"author":"unknown","game":"EXE6/BN6","preview":"home_warp.png"},
{"name":"Mystery Data - Red","type":"object","files":["RedMysteryData.png","RedMysteryData.tsx"],"author":"unknown","game":"Other","preview":"RedMysteryData.png"},
{"name":"HP Colored Tiles","type":"tile","files":["rainbow_floor.png","rainbow_floor.tsx"],"author":"unknown","game":"EXE6/BN6","preview":"rainbow_floor.png"},
{"name":"Custom Conveyers","type":"tile","files":["simple-graveyard-conveyers-64-40-alt.png","simple-graveyard-conveyers-64-40-alt.tsx"],"author":"unknown","game":"Other","preview":"simple-graveyard-conveyers-64-40-alt.png"},
{"name":"Cyber Talisman","type":"object","files":["Talisman.png","Talisman.tsx"],"author":"Claris","game":"EXE6/BN6","preview":"Talisman.png"},
{"name":"Cyber Teddy","type":"object","files":["Teddy.png","Teddy.tsx"],"author":"Claris","game":"EXE6/BN6","preview":"Teddy.png"},
{"name":"Cyber Duck","type":"object","files":["Ducky.png","Ducky.tsx"],"author":"Claris","game":"EXE6/BN6","preview":"Ducky.png"},
{"name":"Vendor Desk","type":"object","files":["vendor_desk.png","vendor_desk.tsx"],"author":"unknown","game":"EXE6/BN6","preview":"vendor_desk.png"},
{"name":"Shanghai Warps","type":"object","files":["ShanghaiWarps1.png","ShanghaiWarps1.tsx"],"type":"object","author":"unknown","game":"Shanghai","preview":"ShanghaiWarps1.png"},
{"name":"Evil Door","type":"object","files":["evildoor_40x74.png","evildoor_40x74.tsx"],"author":"unknown","game":"EXE4/BN4","preview":"evildoor_40x74.png"},
{"name":"Battle Machine","type":"object","files":["BattleMachineBN4.png","BattleMachineBN4.tsx"],"author":"unknown","game":"EXE4/BN4","preview":"BattleMachineBN4.png"},
{"name":"Dark Chip","type":"object","files":["Darkchip13x32.png","Darkchip13x32.tsx"],"author":"unknown","game":"EXE4/BN4","preview":"Darkchip13x32.png"},
{"name":"Graveyard Stairs","type":"tile","files": ["UndernetStairs.png","UndernetStairs.tsx"],"author": "unknown","credit": false,"game": "EXE6/BN6","preview": "UndernetStairs.png"},
{"name":"Graveyard Tiles","type":"tile","files": ["UndernetTiles.png","UndernetTiles.tsx"],"author": "unknown","credit": false,"game": "EXE6/BN6","preview": "UndernetTiles.png"},
{"name":"Graveyward Arrows","type":"tile","files": ["simplegraveyardarrows.tsx","simplegraveyardarrows.png"],"author": "unknown","credit": false,"game": "Other","preview": "simplegraveyardarrows.png"},
{"name":"Graveyard Backward Stairs","type":"tile","files":["cursed-stairs-2.png","cursed-stairs-2.tsx"],"author":"unknown","game":"EXE6/BN6","preview":"cursed-stairs-2.png"},
{"name":"Sky Area 2 Undernet Gate","type":"object","files":["Gate_sky2_exe6.png","Gate_sky2_exe6.tsx"],"author":"Claris","game":"EXE6/BN6","preview":"Gate_sky2_exe6.png"},
{"name":"Sky Area 2 Undernet Skull","type":"object","files":["PurpleArchsSkull.png","PurpleArchsSkull.tsx"],"author":"unknown","game":"EXE6/BN6","preview":"PurpleArchsSkull.png"},
{"name":"Server Warp Pads","files":["DungeonServerWarpPads.png","DungeonServerWarpPads.tsx"],"author":"Claris","game":"EXE6/BN6","preview":"DungeonServerWarpPads.png"},
{"name":"Net Square Stairs","files":["Netopia_Stairs.png","Netopia_Stairs.tsx"],"author":"Claris","game":"EXE2/BN2","preview":"Netopia_Stairs.png"},
{"name":"Liberation Compatible Walls","type":"object","files":["lib_tileset_panels.png","lib_tileset_panels.tsx"],"author":"Quetzen","game":"Custom","preview":"lib_tileset_panels.png"},
{"name":"Liberation Compatible Tileset","type":"tile","files":["lib_tileset.png","lib_tileset.tsx"],"author":"Quetzen","game":"Custom","preview":"lib_tileset.png"},
{"name":"Liberation Compatible Dark Arrow","type":"tile","files":["DarkLiberationArrow.png","DarkLiberationArrow.tsx"],"author":"Quetzen","game":"Custom","preview":"DarkLiberationArrow.png"},
{"name":"Liberation Compatible Arrow","files":["LiberationArrow.png","LiberationArrow.tsx"],"author":"Quetzen","game":"Custom","preview":"LiberationArrow.png"},
{"name":"Liberation Compatible Dark Stairs","type":"tile","files":["DarkLiberationRamp.png","DarkLiberationRamp.tsx"],"author":"Quetzen","game":"Custom","preview":"DarkLiberationRamp.png"},
{"name":"Liberation Compatible Stairs","type":"tile","files":["LiberationRamp.png","LiberationRamp.tsx"],"author":"Quetzen","game":"Custom","preview":"LiberationRamp.png"},
{"name":"Liberation Panels","type":"object","files":["panels.png","panels.tsx"],"author":"unknown","game":"EXE5/BN5","preview":"panels.png"},
{"name":"Liberation Panel Tile","type":"tile","files":["panel base.png","panel base.tsx"],"author":"unknown","game":"EXE5/BN5","preview":"panel base.png"},
{"name":"Liberation Panel Tile Selection","files":["selected tile.png","selected tile.tsx"],"author":"unknown","game":"EXE5/BN5","preview":"selected tile.png"},
{"name":"Generic Stairs","files": ["stairs.png","stairs.tsx"],"author": "unknown","credit": false,"game": "EXE6/BN6","preview": "stairs.png"},
{"name":"ACDC Tree","type":"object","files":["ACDC Tree.tsx","ACDC Tree.png"],"author":"unknown","game":"EXE5/BN5","preview":"ACDC Tree.png"},
{"name":"Bug Frag Trader","type":"object","files":["BugFragTrader_exe3.png","BugFragTrader.tsx"],"author":"unknown","game":"EXE3/BN3","preview":"BugFragTrader_exe3.png"},
{"name":"Breaker Moon Tiles","type":"tile","files":["BreakerMoonAnimated.png","BreakerMoonAnimated.tsx"],"author":"DigitalL33T","game":"Custom","preview":"BreakerMoonAnimated.png"},
{"name":"Beach Area Warp Customized","files":["CusBeachWarp.png","CusBeachWarp.tsx"],"type":"object","author":"unknown","game":"EXE3/BN3","preview":"CusBeachWarp.png"},
{"name":"Gate","type":"object","files":["gate.png","gate.tsx"],"author":"Claris","game":"EXE6/BN6","preview":"gate.png"},
{"name":"Gospel Portal","type":"object","files":["GospelPortal.png","GospelPortal.tsx"],"author":"unknown","game":"EXE2/BN2","preview":"GospelPortal.png"},
{"name":"Secret Area Tiles (1 of 2)","type":"tile","files":["Secret_Area_Prettified_Main.tsx","Secret_Area_Prettified_Main.png"],"author":["Jawnii [Alcor/Kuri]","Claris"],"game":"EXE3/BN3","preview":"Secret_Area_Prettified_Main.png"},
{"name":"Secret Area Tiles (2 of 2)","type":"tile","files":["Secret_Area_Prettified_Walkways.tsx","Secret_Area_Prettified_Walkways.png"],"author":["Jawnii [Alcor/Kuri]","Claris"],"game":"EXE3/BN3","preview":"Secret_Area_Prettified_Walkways.png"},
{"name":"Secret Area Warp","type":"object","files":["Secret_Area_Warp.tsx","Secret_Area_Warp.png"],"author":["Jawnii [Alcor/Kuri]","Claris"],"game":"EXE3/BN3","preview":"Secret_Area_Warp.png"},
{"name":"Secret Area Arrows","type":"tile","files":["SecretArrows.tsx","SecretArrows.png"],"author":["Jawnii [Alcor/Kuri]","Quetzen"],"game":"EXE3/BN3","preview":"SecretArrows.png"},
{"name":"Secret Area Stairs","type":"tile","files":["SecretStairs.tsx","SecretStairs.png"],"author":["Jawnii [Alcor/Kuri]","Quetzen"],"game":"EXE3/BN3","preview":"SecretStairs.png"},
{"name":"Secret Area Water (BN3)","type":"tile","files":["WaterTilesV2.tsx","WaterTilesV2.png"],"author":"Jawnii [Alcor/Kuri]","game":"Custom","preview":"WaterTilesV2.png"},
{"name":"Secret Area Tiles - Recolored (1 of 2)","type":"tile","files":["Secret_Area_GreenAndWhite_main.tsx","Secret_Area_GreenAndWhite_main.png"],"author":"Jawnii [Alcor/Kuri]","game":"EXE3/BN3","preview":"Secret_Area_GreenAndWhite_main.png"},
{"name":"Secret Area Tiles - Recolored (2 of 2)","type":"tile","files":["Secret_Area_GreenAndWhite_Walkways.tsx","Secret_Area_GreenAndWhite_Walkways.png"],"author":"Jawnii [Alcor/Kuri]","game":"EXE3/BN3","preview":"Secret_Area_GreenAndWhite_Walkways.png"},
{"name":"ACDC Generic House (1 of 7)","files":["House A.png","House A.tsx"],"author":"Claris","game":"Custom","preview":"House A.png"},
{"name":"ACDC Generic House (2 of 7)","files":["House B.png","House B.tsx"],"author":"Claris","game":"Custom","preview":"House B.png"},
{"name":"ACDC Generic House (3 of 7)","files":["House C.png","House C.tsx"],"author":"Claris","game":"Custom","preview":"House C.png"},
{"name":"ACDC Generic House (4 of 7)","files":["House D.png","House D.tsx"],"author":"Claris","game":"Custom","preview":"House D.png"},
{"name":"ACDC Generic House (5 of 7)","files":["House E.png","House E.tsx"],"author":"Claris","game":"Custom","preview":"House E.png"},
{"name":"ACDC Generic House (6 of 7)","files":["House F.png","House F.tsx"],"author":"Claris","game":"Custom","preview":"House F.png"},
{"name":"ACDC Generic House (7 of 7)","files":["Higsby's But Not.png","Higsby's But Not.tsx"],"author":"Claris","game":"Custom","preview":"Higsby's But Not.png"},
{"name":"ACDC Dex House","files":["MC House Dex.png","MC House Dex.tsx"],"author":"Claris","game":"EXE5/BN5","preview":"MC House Dex.png"},
{"name":"ACDC Lan House","files":["MC House Lan.png","MC House Lan.tsx"],"author":"Claris","game":"EXE5/BN5","preview":"MC House Lan.png"},
{"name":"ACDC Mayl House","files":["MC House Meiru.png","MC House Meiru.tsx"],"author":"Claris","game":"EXE5/BN5","preview":"MC House Meiru.png"},
{"name":"ACDC Metro","files":["Metro Building.png","Metro Building.tsx"],"author":"Claris","game":"EXE5/BN5","preview":"Metro Building.png"},
{"name":"ACDC Squirrel","files":["Squirrel.png","Squirrel.tsx"],"author":"Claris","game":"Other","preview":"Squirrel.png"},
{"name":"ACDC Bus Stop","files":["Bus Stop.png","Bus Stop.tsx"],"author":"Claris","game":"Other","preview":"Bus Stop.png"},
{"name":"ACDC Elephant Slide","files":["Elephant Slide.png","Elephant Slide.tsx"],"author":"Claris","game":"Other","preview":"Elephant Slide.png"},
{"name":"ACDC Park Bench","files":["Park Bench.png","Park Bench.tsx"],"author":"Claris","game":"Other","preview":"Park Bench.png"},
{"name":"ACDC Play Dome","files":["Play Dome.png","Play Dome.tsx"],"author":["Claris","Quetzen"],"game":"Other","preview":"Play Dome.png"},
{"name":"Cyber Elephant Slide","files":["Cyber Elephant Slide.png","Cyber Elephant Slide.tsx"],"author":"Claris","game":"Other","preview":"Cyber Elephant Slide.png"},
{"name":"Cyber Play Dome","files":["Cyber Play Dome.png","Cyber Play Dome.tsx"],"author":["Claris","Quetzen"],"game":"Other","preview":"Cyber Play Dome.png"},
{"name":"Chip Traders","files": ["Traders.png","Traders.tsx"],"author": "unknown","BlaXun": false,"game": "Other","preview": "Traders.png"},
{"name":"Boktai Dolls","files":["BoktaiDolls28x33.png","BoktaiDolls28x33.tsx"],"author":"unknown","game":"EXE4/BN4","preview":"BoktaiDolls28x33.png"},
{"name":"Bridge Tile","files":["BridgeTile.png","BridgeTile.tsx"],"author":"FrozenLake","game":"Other","preview":"BridgeTile.png"},
{"name":"Glow Tileset - Arrows","files":["GlowArrows.png","GlowArrows.tsx"],"author":"unknown","game":"Custom","preview":"GlowArrows.png"},
{"name":"Glow Tileset - Large","files":["GlowLrg.png","GlowLrg.tsx"],"author":"unknown","game":"Custom","preview":"GlowLrg.png"},
{"name":"Glow Tileset - Small","files":["GlowSm.png","GlowSm.tsx"],"author":"unknown","game":"Custom","preview":"GlowSm.png"},
{"name":"Glow Tileset - Stairs","files":["GlowStairs.png","GlowStairs.tsx"],"author":"unknown","game":"Custom","preview":"GlowStairs.png"},
{"name":"Holo Tile (BN6)","files":["HoloPanelz.tsx","HoloPanelz.png"],"author":"unknown","game":"Custom","preview":"HoloPanelz.png"},
{"name":"Noise Wave Entrance","files":["NoiseWaveEntrance.png","NoiseWaveEntrance.tsx"],"author":"FrozenLake","game":"Other","preview":"NoiseWaveEntrance.png"},
{"name":"Shademan Comp Warp Animation","files":["ShademanCompWarpAnimation.png","ShademanCompWarpAnimation.tsx"],"author":"unknown","game":"EXE4/BN4","preview":"ShademanCompWarpAnimation.png"},
{"name":"Undernet Statue","type":"object","files":["UndernetStatue.png","UndernetStatue.tsx"],"author":"unknown","game":"EXE3/BN3","preview":"UndernetStatue.png"},
{"name":"Flame Door","files":["SDoor.png","SDoor.tsx"],"author":"unknown","game":"Other","preview":"SDoor.png"},
{"name":"Warp Library","files":["warp_lib.png","warp_lib.tsx"],"author":"unknown","game":"EXE3/BN3","preview":"warp_lib.png"},
{"name":"Warp to HP","files":["Warp_tohp_exe2.png","Warp_tohp_exe2.tsx"],"author":"unknown","game":"EXE2/BN2","preview":"Warp_tohp_exe2.png"},
{"name":"Warp to Square Entrance","files":["Warp_tosqrentr_exe2.png","Warp_tosqrentr_exe2.tsx"],"author":"unknown","game":"EXE2/BN2","preview":"Warp_tosqrentr_exe2.png"},
{"name":"Warp","files":["warp.png","warp.tsx"],"author":"unknown","game":"EXE3/BN3","preview":"warp.png"},
{"name":"Advertising Billboard","files":["AdvertisingBillboard.png","AdvertisingBillboard.tsx"],"author":"unknown","game":"Other","preview":"AdvertisingBillboard.png"},
{"name":"Chains","files":["chainOW64x40.png","chainOW64x40.tsx"],"author":"unknown","game":"Other","preview":"chainOW64x40.png"},
{"name":"Cracked Floor","files":["CrackedFloorForKeristero.png","CrackedFloorForKeristero.tsx"],"author":"unknown","game":"Other","preview":"CrackedFloorForKeristero.png"},
{"name":"HP Warp - Blue","files":["hp_warp_blue.png","hp_warp_blue.tsx"],"author":"Claris","game":"Other","preview":"hp_warp_blue.png"},
{"name":"HP Warp","files":["hp_warp.png","hp_warp.tsx"],"author":"unknown","game":"Other","preview":"hp_warp.png"},
{"name":"WWW Warp","files":["Napalm Warp.png","Napalm Warp.tsx"],"author":"unknown","game":"Other","preview":"Napalm Warp.png"},
{"name":"Server Warp","files":["ServerWarp.png","ServerWarp.tsx"],"author":"unknown","game":"Other","preview":"ServerWarp.png"},
{"name":"Tiles Colorful","files": ["TilesColorful.png","TilesColorful.tsx"],"author": "D3str0y3d","credit": false,"game": "Other","preview": "TilesColorful.png"},
{"name":"Beyblade","type":"object","files":["beyblade.tsx","beyblade.png"],"author":"Cyan","game":"EXE4/BN4","preview":"beyblade.png"},
{"name":"Bat Device","type":"object","files":["device.png","device.tsx"],"author":"Cyan","game":"EXE4/BN4","preview":"device.png"},
{"name":"Bugfrag","type":"object","files":["frag.png","frag.tsx"],"author":"Cyan","game":"EXE3/BN3","preview":"frag.png"},
{"name":"Kabobs","type":"object","files":["kabob.png","kabob.tsx"],"author":"Cyan","game":"EXE2/BN2","preview":"kabob.png"},
{"name":"Robot Toy","type":"object","files":["toy.tsx","toy.png"],"author":"Cyan","game":"EXE4/BN4","preview":"toy.png"},
{"name":"Vines","type":"object","files":["vines.png","vines.tsx"],"author":"Cyan","game":"EXE3/BN3","preview":"vines.png"},
{"name":"Alpha Security Pillar","type":"object","files":["alphapillar.png","alphapillar.tsx"],"author":"unknown","game":"EXE3/BN3","preview":"alphapillar.png"},
{"name":"Undernet Warp Overlay","type":"object","files":["Bn3UndernetFlashingWarp.png","Bn3UndernetFlashingWarp.tsx"],"author":"unknown","game":"EXE3/BN3","preview":"Bn3UndernetFlashingWarp.png"},
{"name":"Undernet Warp Overlay","type":"object","files":["Bn3UndernetFlashingWarpVariant2.png","Bn3UndernetFlashingWarpVariant2.tsx"],"author":"unknown","game":"EXE3/BN3","preview":"Bn3UndernetFlashingWarpVariant2.png"},
{"name":"Undernet Warp","type":"object","files":["BN3UndernetWarpVariant1.png","BN3UndernetWarpVariant1.tsx"],"author":"unknown","game":"EXE3/BN3","preview":"BN3UndernetWarpVariant1.png"},
{"name":"Undernet Square Warp","type":"object","files":["BN3UndernetWarpVariant2.png","BN3UndernetWarpVariant2.tsx"],"author":"unknown","game":"EXE3/BN3","preview":"BN3UndernetWarpVariant2.png"},
{"name":"Lan HP Tile Overlay","type":"object","files":["LanHpAnimatedTiles.png","LanHpAnimatedTiles.tsx"],"author":"unknown","game":"EXE4/BN4","preview":"LanHpAnimatedTiles.png"},
{"name":"Secret Area Entrance Warp","type":"object","files":["UndernetInteractWarp.png","UndernetInteractWarp.tsx"],"author":"unknown","game":"EXE3/BN3","preview":"UndernetInteractWarp.png"},
{"name":"Aqua Grabber 3000","type":"object","files":["AquaGrabber3000small.tsx","AquaGrabber3000small.png"],"author":"D3str0y3d","game":"Custom","preview":"AquaGrabber3000small.png"},
{"name":"Meteor Comp Tileset","type":"","files":["BN4_MeteorComp","BN4_MeteorComp.png"],"author":"Quetzen","game":"EXE4/BN4","preview":"BN4_MeteorComp.png"},
{"name":"Meteor Comp Platform","type":"","files":["BN4_MeteorComp_platform.tsx","BN4_MeteorComp_platform.png"],"author":"Quetzen","game":"EXE4/BN4","preview":"BN4_MeteorComp_platform.png"},
{"name":"Vision Burst Door","type":"object","files":["BN5_vision_door.tsx","BN5_vision_door.png"],"author":"Quetzen","game":"EXE5/BN5","preview":"BN5_vision_door.png"},
{"name":"Clouds","type":"object","files":["Clouds.tsx","Clouds.png"],"author":"Quetzen","game":"EXE5/BN5","preview":"Clouds.png"},
{"name":"Generic Comp Tileset","type":"tile","files":["EXE3_computer_tileset.tsx","EXE3_computer_tileset.png"],"author":"Quetzen","game":"EXE3/BN3","preview":"EXE3_computer_tileset.png"},
{"name":"Security Cubes","type":"object","files":["EXE3_cubes.tsx","EXE3_cubes.png"],"author":"Quetzen","game":"EXE3/BN3","preview":"EXE3_cubes.png"},
{"name":"Boss Marker","type":"object","files":["EXE6_boss_markers.tsx","EXE6_boss_markers.png"],"author":"Quetzen","game":"EXE6/BN6","preview":"EXE6_boss_markers.png"},
{"name":"HP Shortcut","type":"object","files":["EXE6_Shortcuts.tsx","EXE6_Shortcuts.png"],"author":"Quetzen","game":"EXE6/BN6","preview":"EXE6_Shortcuts.png"},
{"name":"Bandage Tornado","type":"object","files":["obstacle_bandages.tsx","obstacle_bandages.png"],"author":"Quetzen","game":"EXE4.5","preview":"obstacle_bandages.png"},
{"name":"Large Fires (1/2)","type":"object","files":["obstacle_fire_1.tsx","obstacle_fire_1.png"],"author":"Quetzen","game":"EXE3/BN3","preview":"obstacle_fire_1.png"},
{"name":"Large Fires (2/2)","type":"object","files":["obstacle_fire_2.tsx","obstacle_fire_2.png"],"author":"Quetzen","game":"EXE6/BN6","preview":"obstacle_fire_2.png"},
{"name":"Stones","type":"objects","files":["obstacle_stone.tsx","obstacle_stone.png"],"author":"Quetzen","game":"EXE5/BN5","preview":"obstacle_stone.png"},
{"name":"Stump","type":"object","files":["obstacle_stump.tsx","obstacle_stump.png"],"author":"Quetzen","game":"Other","preview":"obstacle_stump.png"},
{"name":"Podium","type":"object","files":["Podium.tsx","Podium.png"],"author":"Quetzen","game":"EXE5/BN5","preview":"Podium.png"},
{"name":"Roadblock","type":"object","files":["Roadblock.tsx","Roadblock.png"],"author":"Quetzen","game":"EXE2/BN2","preview":"Roadblock.png"},
{"name":"Sewage Station (1/3)","type":"object","files":["Sewage_station_base.tsx","Sewage_station_base.png"],"author":"Quetzen","game":"EXE6/BN6","preview":"Sewage_station_base.png"},
{"name":"Sewage Station (2/3)","type":"object","files":["Sewage_station_upper_layer_1.tsx","Sewage_station_upper_layer_1.png"],"author":"Quetzen","game":"EXE6/BN6","preview":"Sewage_station_upper_layer_1.png"},
{"name":"Sewage Station (3/3)","type":"object","files":["extra_liquids.tsx","extra_liquids.png"],"author":"Quetzen","game":"EXE6/BN6","preview":"extra_liquids.png"},
{"name":"Water Station (1/2)","type":"object","files":["Water_station_base.tsx","Water_station_base.png"],"author":"Quetzen","game":"EXE6/BN6","preview":"Water_station_base.png"},
{"name":"Water Station (1/2)","type":"object","files":["Water_station_upper_layer_1.tsx","Water_station_upper_layer_1.png"],"author":"Quetzen","game":"EXE6/BN6","preview":"Water_station_upper_layer_1.png"},
{"name":"Poison Station","type":"object","files":["fountain.tsx","fountain.png"],"author":"Cyan","game":"EXE6/BN6","preview":"fountain.png"},
{"name":"Cyber Tree","type":"object","files":["tree.tsx","tree.png"],"author":"Quetzen","game":"EXE6/BN6","preview":"tree.png"},
{"name":"Tiny Desk","type":"object","files":["tiny_desks.tsx","tiny_desks.png"],"author":"Quetzen","game":"EXE4.5","preview":"tiny_desks.png"},
{"name":"Toy Robo Comp","type":"tile","files":["Toy_Robo.tsx","Toy_Robo.png"],"author":"Quetzen","game":"EXE4/BN4","preview":"Toy_Robo.png"},
{"name":"Vending Machines","type":"object","files":["vendmach.tsx","vendmach.png"],"author":"Quetzen","game":"Other","preview":"vendmach.png"},
{"name":"Junk Piles","type":"object","files":["Junkpiles.tsx","Junkpiles.png"],"author":"Quetzen","game":"EXE4/BN4","preview":"Junkpiles.png"},
{"name":"Freezeman Ice","type":"object","files":["Freezeman Ice.tsx","Freezeman Ice.png"],"author":"Quetzen","game":"EXE2/BN2","preview":"Freezeman Ice.png"},
{"name":"Trees","type":"object","files":["exe45_trees.png","exe45_trees.tsx"],"author":"Quetzen","game":"EXE4.5","preview":"exe45_trees.png"},
{"name":"Wave Roads Decoration (1 of 2)","type":"object","files":["WaveRoadsLBlocks.tsx","WaveRoadsLBlocks.png"],"author":"D3str0y3d","game":"Other","preview":"WaveRoadsLBlocks.png"},
{"name":"Wave Roads Decoration (2 of 2)","type":"object","files":["WaveRoadAccentAnimationsStraightLine.tsx","WaveRoadAccentAnimationsStraightLine.png"],"author":"D3str0y3d","game":"Other","preview":"WaveRoadAccentAnimationsStraightLine.png"},

/*

//this is an empty dictionary you can use to make new entries (type can be object or tile)

{"name":"","type":"","files":["",""],"author":"unknown","game":"","preview":""},

"type":"object",
"type":"tile",

*/

];